// Seed data for cars

import type { Car } from "./types"

export const defaultCars: Car[] = [
  {
    id: "car-1",
    name: "Swift",
    model: "Maruti Swift 2023",
    type: "Hatchback",
    hourlyRate: 150,
    dailyRate: 1200,
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=400&h=300&fit=crop&auto=format",
    description: "Compact and efficient hatchback, perfect for city errands and short trips.",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "car-2",
    name: "City",
    model: "Honda City 2022",
    type: "Sedan",
    hourlyRate: 220,
    dailyRate: 1700,
    image: "https://images.unsplash.com/photo-1549924231-f129b911e442?w=400&h=300&fit=crop&auto=format",
    description: "Comfortable sedan with spacious seating, ideal for longer rides.",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "car-3",
    name: "Creta",
    model: "Hyundai Creta 2023",
    type: "SUV",
    hourlyRate: 300,
    dailyRate: 2200,
    image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=400&h=300&fit=crop&auto=format",
    description: "Versatile SUV with ample boot space and high ground clearance.",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "car-4",
    name: "XUV700",
    model: "Mahindra XUV700 2024",
    type: "XUV",
    hourlyRate: 380,
    dailyRate: 2800,
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400&h=300&fit=crop&auto=format",
    description: "Premium XUV with powerful performance and modern tech features.",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "car-5",
    name: "WagonR",
    model: "Maruti WagonR 2021",
    type: "Hatchback",
    hourlyRate: 130,
    dailyRate: 1000,
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400&h=300&fit=crop&auto=format",
    description: "Budget-friendly mini with great mileage for daily commuting.",
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
]
